#!/usr/bin/perl
use PARI::822;

PARI::822::read(\%funcs, "pari.desc");

open (FILE, "../../doc/usersFUNCS.tex") || die;
while (<FILE>)
{
  if (/^% *SECTION *: *(.*) */)
  {
    my ($sec) = $1;
    for ( sort grep { $funcs{$_}->{Section} eq $sec } keys %funcs ) {
      my ($fun) = $funcs{$_};
      my ($doc) = $fun->{Doc};
      next if (!defined($doc));

      my ($args)  = $fun->{Help};
      $args =~ s/ *:.*//s;

      my ($v);
      if ($args =~ /^\w+=\w+\(\)/) { $args = $v = ''; }
      else
      {
        $args =~ s/^[^(]*\((.*)\)/$1/; # args proper
        $v = $args;
        $v =~ s/([{}&])/\\$1/g;
        $v =~ s/\^(\d+)/^{$1}/g;
        $v =~ s/\[\]/[\\,]/g;
        $v =~ s/(\w\w+)/\\var{$1}/g;
        $v =~ s/\^([a-z])/\\hbox{\\kbd{\\pow}}$1/g;
        $v =~ s/\\var{flag}/\\fl/g;

        $v = "\$($v)\$";
      }

      if ($doc !~ /\\syn\w*{/ && $sec !~ /programming/) {
        my ($Cname) = $fun->{'C-Name'};
        my ($proto) = $fun->{Prototype};
        my ($w) = $args;
        $w =~ s/[{}]//g;
        $w =~ s/=[^,)]*//g; # default values

        $type = "GEN";
        $type = "long" if ($proto =~ /^l/);
        $type = "void" if ($proto =~ /^v/);

        $args = '';
        for ( split(/, */, $w) ) 
        {
          $args .= "GEN $_,"

        }
        $args .= " long prec" if ($proto =~ /p$/);
        $args =~ s/,$//;

        $doc .= "\n\nThe library syntax is \\fun{$type}{$Cname}{$args}."
      }
      print "\n\\subsecidx{$_}$v:\\label{se:$_} $doc\n";
    }
    next;
  }
  print;
}
