#define __MULII_KARATSUBA_LIMIT         -1
#define __SQRI_KARATSUBA_LIMIT          -1
#define __MULII_FFT_LIMIT               -1
#define __SQRI_FFT_LIMIT                -1
#define __MULRR_MULII_LIMIT             15
#define __Fp_POW_REDC_LIMIT              6
#define __Fp_POW_BARRETT_LIMIT          83
#define __INVNEWTON_LIMIT              464
#define __DIVRR_GMP_LIMIT                4
#define __EXPNEWTON_LIMIT               66
#define __LOGAGM_LIMIT                  10
#define __LOGAGMCX_LIMIT                33
#define __AGM_ATAN_LIMIT                60
#define __INVMOD_GMP_LIMIT               3
#define __Flx_MUL_KARATSUBA_LIMIT      155
#define __Flx_SQR_KARATSUBA_LIMIT      226
#define __Flx_MUL_MULII_LIMIT            6
#define __Flx_SQR_SQRI_LIMIT             5
#define __Flx_MUL_HALFMULII_LIMIT        6
#define __Flx_SQR_HALFSQRI_LIMIT         3
#define __Flx_INVMONTGOMERY_LIMIT      804
#define __Flx_REM_MONTGOMERY_LIMIT     605
#define __Flx_POW_MONTGOMERY_LIMIT     216
#define __Flx_HALFGCD_LIMIT             94
#define __Flx_GCD_LIMIT                718
#define __Flx_EXTGCD_LIMIT             180
#define __FpX_INVMONTGOMERY_LIMIT      106
#define __FpX_REM_MONTGOMERY_LIMIT      93
#define __FpX_POW_MONTGOMERY_LIMIT      32
#define __FpX_HALFGCD_LIMIT             57
#define __FpX_GCD_LIMIT                354
#define __FpX_EXTGCD_LIMIT              79
#define __RgX_MUL_LIMIT                 11
#define __RgX_SQR_LIMIT                 46
