#! /bin/sh
srcbase="`echo src/*/*.[chy] | sed -e 's,src/language/parse\.[ch],,g'`"
CFILES="$srcbase src/*/*/*.[ch] examples/*.c examples/*.gp"
docbase="`echo doc/*.tex | sed -e 's,doc/usersch3.tex,,'`"
OFILES="$docbase AUTHORS COMPAT NEW TODO CHANGES MACHINES src/test/in/* src/functions/*/*"
SCRIPTS="config/* src/test/dotest"
err=0;
if grep ' $' $CFILES $OFILES $SCRIPTS; then
  echo "BUG: trailing spaces found."
  err=1;
fi
if grep '	' $CFILES $OFILES; then
  echo "BUG: TAB found."
  err=1;
fi
if grep '	$' $SCRIPTS; then
  echo "BUG: TAB found in scripts."
  err=1;
fi
exit $err
