#! /bin/sh
K=../src/kernel
file="$K/$1"
knone=$K/none
echo "#ifndef ASMINLINE"
for i in `grep '^NOASM' $file`; do
  case $i in
    NOASM);;
    *) cat $knone/$i.h;;
  esac;
done
echo "#endif"
cat $file
for i in `grep '^ALWAYS' $file`; do
  case $i in
    ALWAYS);;
    *) cat $knone/$i.h;;
  esac;
done
