#define __MULII_KARATSUBA_LIMIT         18
#define __SQRI_KARATSUBA_LIMIT          34
#define __MULII_FFT_LIMIT             1386
#define __SQRI_FFT_LIMIT              1386
#define __MULRR_MULII_LIMIT            191
#define __Fp_POW_REDC_LIMIT             99
#define __Fp_POW_BARRETT_LIMIT          97
#define __INVNEWTON_LIMIT              656
#define __DIVRR_GMP_LIMIT               -1
#define __EXPNEWTON_LIMIT               66
#define __LOGAGM_LIMIT                  24
#define __LOGAGMCX_LIMIT                30
#define __AGM_ATAN_LIMIT                66
#define __INVMOD_GMP_LIMIT              -1
#define __Flx_MUL_KARATSUBA_LIMIT      115
#define __Flx_SQR_KARATSUBA_LIMIT      264
#define __Flx_MUL_HALFMULII_LIMIT        9
#define __Flx_SQR_HALFSQRI_LIMIT         3
#define __Flx_MUL_MULII_LIMIT         6517
#define __Flx_SQR_SQRI_LIMIT          7265
#define __Flx_MUL_MULII2_LIMIT           5
#define __Flx_SQR_SQRI2_LIMIT            9
#define __Flx_INVMONTGOMERY_LIMIT     7426
#define __Flx_REM_MONTGOMERY_LIMIT    3407
#define __Flx_POW_MONTGOMERY_LIMIT    1015
#define __Flx_HALFGCD_LIMIT             74
#define __Flx_GCD_LIMIT               3041
#define __Flx_EXTGCD_LIMIT             280
#define __FpX_INVMONTGOMERY_LIMIT      407
#define __FpX_REM_MONTGOMERY_LIMIT     407
#define __FpX_POW_MONTGOMERY_LIMIT     176
#define __FpX_HALFGCD_LIMIT            115
#define __FpX_GCD_LIMIT               1292
#define __FpX_EXTGCD_LIMIT             222
#define __RgX_MUL_LIMIT                  5
#define __RgX_SQR_LIMIT                 27
