#define __MULII_KARATSUBA_LIMIT         17
#define __SQRI_KARATSUBA_LIMIT          40
#define __MULII_FFT_LIMIT             1386
#define __SQRI_FFT_LIMIT              1386
#define __MULRR_MULII_LIMIT            183
#define __Fp_POW_REDC_LIMIT             99
#define __Fp_POW_BARRETT_LIMIT          97
#define __INVNEWTON_LIMIT              656
#define __DIVRR_GMP_LIMIT               -1
#define __EXPNEWTON_LIMIT               66
#define __LOGAGM_LIMIT                  23
#define __LOGAGMCX_LIMIT                32
#define __AGM_ATAN_LIMIT                63
#define __INVMOD_GMP_LIMIT              -1
#define __Flx_MUL_KARATSUBA_LIMIT      107
#define __Flx_SQR_KARATSUBA_LIMIT      232
#define __Flx_MUL_MULII_LIMIT         7123
#define __Flx_SQR_SQRI_LIMIT          6327
#define __Flx_MUL_HALFMULII_LIMIT       10
#define __Flx_SQR_HALFSQRI_LIMIT         3
#define __Flx_INVMONTGOMERY_LIMIT     6737
#define __Flx_REM_MONTGOMERY_LIMIT    2671
#define __Flx_POW_MONTGOMERY_LIMIT     874
#define __Flx_HALFGCD_LIMIT             65
#define __Flx_GCD_LIMIT               2765
#define __Flx_EXTGCD_LIMIT             250
#define __FpX_INVMONTGOMERY_LIMIT      427
#define __FpX_REM_MONTGOMERY_LIMIT     407
#define __FpX_POW_MONTGOMERY_LIMIT     172
#define __FpX_HALFGCD_LIMIT            117
#define __FpX_GCD_LIMIT               1292
#define __FpX_EXTGCD_LIMIT             222
#define __RgX_MUL_LIMIT                  5
#define __RgX_SQR_LIMIT                 27
